[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim', 'denite.nvim']

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_event = 'TextYankPost'
on_source = ['unite.vim', 'denite.nvim']

[[plugins]]
repo = 'vim-denops/denops.vim'

# filer
# Menuペインが文字化けしているので以下を対応すること
# 1. `brew install --cask font-hack-nerd-font`を実行してFontをインストールする
# 2. iterm2の設定を変更する／Font -> Hack Nerd Font, Non-ASCII Font -> Hak Nerd Font
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
  let g:fern#default_hidden=1
'''

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
  let g:fern#renderer = 'nerdfont'
'''

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
  augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
    autocmd FileType nerdtree,startify call glyph_palette#apply()
  augroup END
'''

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
let g:winresizer_start_key = '<C-T>'
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
hook_add = 'source ~/.config/nvim/coc-setting.vim'
marged = 0
rev = 'release'

# go
[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']
[[plugins]]
repo = 'buoto/gotests-vim'

# statusline
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
        \ 'colorscheme': 'wombat',
        \ 'active': {
        \   'left': [ 
        \     [ 'mode', 'paste' ],
        \     [ 'gitbranch', 'readonly', 'filename', 'modified' ] 
        \   ]},
        \ 'component_function': {'gitbranch': 'gitbranch#name', 'filename': 'LightlineFilename'}}
    set laststatus=2
    set noshowmode
    function! LightlineFilename()
      return expand('%')
    endfunction
'''
[[plugins]]
repo = 'itchyny/vim-gitbranch'

# comment out
[[plugins]]
repo = 'tomtom/tcomment_vim'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'

# text
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'Raimondi/delimitMate'
